currency_app:
  url: "http://api.exchangeratesapi.io/v1/"
  last_url: "latest"
  access_key: "a0ec6e79d368336768d78dd4bfc06e1f"
  base: "EUR"
  symbols:
    - 'UAH'
    - 'GBP'
    - 'USD'
    - 'PLN'
    - 'RUB'
  directory: "data/currencies"

rd_dreams_app:
  url: "https://robot-dreams-de-api.herokuapp.com"
  content-type: "application/json"
  username: "rd_dreams"
  password: "djT6LasE"
  auth_endpoint: "/auth"
  endpoint: "/out_of_stock"
  auth_prefix: "JWT "
  directory: "data/rd_payload"
  payload_dates:
    - '2021-07-05'
    - '2021-07-06'

daily_etl:
  sources:
    api:
      - "api name"
    postgres_pagila:
      - actor
      - category
      - film
      - film_actor
      - film_category
      - language
    postgres_dshop:
      - aisles
      - clients
      - departments
      - orders
      - products

